[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"

[[services]]
  name = "sublet"

  [services.env]
    NODE_ENV = "production"
    PORT = "3000"
